### ISSUE TITLE
Compiling fails with --prod (aot)

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#100]
I've created a public repo with simple example and instructions in readme.md to reproduce the error.

Can clone the repo here:

git clone https://github.com/mtsang/issue-1

to install
```
npm install @ionic/app-scripts@latest --save-dev
npm install
```

you can see it runs and loads forms from form.io service
```
npm run ionic:serve
```
works.

it also builds in dev mode:
```
npm run ionic:build
```
works.

However there are errors with prod (aot)
```
npm run ionic:build --prod
```
fails.

will result in the error:
```
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function 

            calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 

            resolving symbol Injectable in 

            node_modules/ng2-formio/node_modules/@angular/core/core.d.ts,

            resolving symbol FormioLoader in 

            node_modules/ng2-formio/src/formio.loader.d.ts, resolving 

            symbol FormioLoader in 

            node_modules/ng2-formio/src/formio.loader.d.ts 

Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in 
node_modules/ng2-formio/node_modules/@angular/core/core.d.ts, resolving symbol FormioLoader in node_modules/ng2-formio/src/formio.loader.d.ts, resolving symbol FormioLoader in node_modules/ng2-formio/src/formio.loader.d.ts

    at syntaxError (node_modules/@angular/compiler/bundles/compiler.umd.js:1513:34)

    at simplifyInContext (node_modules/@angular/compiler/bundles/compiler.umd.js:23316:23)

    at StaticReflector.simplify (node_modules/@angular/compiler/bundles/compiler.umd.js:23328:13)

    at StaticReflector.annotations (node_modules/@angular/compiler/bundles/compiler.umd.js:22794:60)

    at NgModuleResolver.resolve (node_modules/@angular/compiler/bundles/compiler.umd.js:13352:70)

    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:13937:60)

    at addNgModule (node_modules/@angular/compiler/bundles/compiler.umd.js:22526:58)

    at node_modules/@angular/compiler/bundles/compiler.umd.js:22537:14

    at Array.forEach (native)

    at _createNgModules (node_modules/@angular/compiler/bundles/compiler.umd.js:22536:26)


```

**Comment by travist** [comment]
So I am able to reproduce this, but I honestly don't know what it will take to fix it. I have been scouring the web and apparently this is a very widespread issue with a lot of other projects. Anyone have any ideas how to fix this that would be greatly appreciated.

**Comment by mtsang** [comment]
using ionic2: similar errors

[00:16:48]  Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function 
            calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 
            resolving symbol Injectable in 
            node_modules/ng2-formio/node_modules/@angular/core/core.d.ts, resolving 
            symbol FormioAppConfig in node_modules/ng2-formio/src/formio.config.d.ts, 
            resolving symbol FormioAppConfig in 
            node_modules/ng2-formio/src/formio.config.d.ts 
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in node_modules/ng2-formio/node_modules/@angular/core/core.d.ts, resolving symbol FormioAppConfig in node_modules/ng2-formio/src/formio.config.d.ts, resolving symbol FormioAppConfig in node_modules/ng2-formio/src/formio.config.d.ts
    at SyntaxError.BaseError [as constructor] (node_modules/@angular/compiler/bundles/compiler.umd.js:1597:31)
    at new SyntaxError (node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at simplifyInContext (node_modules/@angular/compiler/bundles/compiler.umd.js:25774:27)
    at StaticReflector.simplify (node_modules/@angular/compiler/bundles/compiler.umd.js:25786:17)
    at StaticReflector.annotations (node_modules/@angular/compiler/bundles/compiler.umd.js:25282:64)
    at NgModuleResolver.resolve (node_modules/@angular/compiler/bundles/compiler.umd.js:17762:86)
    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:18263:64)
    at addNgModule (node_modules/@angular/compiler/bundles/compiler.umd.js:25044:62)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:25055:18
    at Array.forEach (native)

**Comment by mtsang** [comment]
I was able to finally solve these errors by putting various libraries into peerDependencies.
(e.g.   "peerDependencies": {
    "@angular/common": "^2.4.10",
    "@angular/compiler": "^2.4.10",
    "@angular/compiler-cli": "^2.4.10"
  },

However, compilation is ends up being stuck at issue #90

**Comment by mtsang** [comment]
This is resolvable by adding the angular/core etc to peerDeps!

**Comment by travist** [comment]
Awesome! Thank you! But do we need to add that peerDep to the package.json of this project?

**Comment by mtsang** [comment]
i will try it and let you know.

**Comment by qasimraza1979** [comment]
Good @mikethm , could you please provide a bit more info.  Here below is my part of package.json


"peerDependencies": {
    "@angular/common": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "ionic": "3.9.2",
    "ionic-angular": "^3.7.1",
    "ionicons": "3.0.0",
    "rxjs": "5.4.3",
    "zone.js": "0.8.18"    
},
"dependencies": {
    "@angular/animations": "4.4.3",
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@angular/platform-server": "4.4.3",
    "@angular/router": "4.4.3",
    "@angular/upgrade": "4.4.3",
    "@ionic-native/core": "3.12.1",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.7.1",
    "ionicons": "3.0.0",
    "ionic": "3.9.2",
    "rxjs": "5.4.3",
    "zone.js": "0.8.18"
},
"devDependencies": {
    "@ionic/app-scripts": "2.1.4",
    "@monsenso/components": "0.0.2-prerelease.14",
    "@monsenso/model": "1.2.3-prerelease.108",
    "@monsenso/user-api": "3.1.0-prerelease.21",   
    "@types/core-js": "0.9.43",
    "@types/jasmine": "^2.5.41",
    "@types/node": "^8.0.33",    
    "angular-router-loader": "^0.6.0",
    "angular2-template-loader": "^0.6.2",
    "codelyzer": "^3.2.0",
    "del-cli": "^1.1.0",
    "extract-text-webpack-plugin": "3.0.0",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.28.0",
    "ionic-mocks": "^1.0.1",
    "jasmine": "^2.8.0",
    "jasmine-core": "^2.8.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "2.0.4",
    "lite-server": "^2.3.0",
    "node-sass": "^4.5.0",
    "null-loader": "^0.1.1",
    "raw-loader": "^0.5.1",
    "sass-lint": "^1.11.1",
    "tslint": "^5.0.0",
    "ts-loader": "^2.3.7",
    "typescript": "2.3.4",
    "webpack": "^3.0.0"
  }
