### ISSUE TITLE
continuous spinner when ng2-formio compiled on ios when app is offline

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#108]
when ng2-formio rendering on an app that is compiled to ios platform, if the app goes offline, there is a continuous spinner, making it impossible to interact with the app. 
due to 'loader-wrapper' class

**Comment by travist** [comment]
This wrapper is overlapping other areas besides the form? I did make a change with the latest core renderer on how this loader works and thought I made it so that it would not overlap other areas on the page. Let me know otherwise since it may be behaving different in your app.

**Comment by mtsang** [comment]
it just appears over the ng2-formio component. but the expected  behaviour is that forms loaded via raw JSON would still be visible etc... this behaviour also seems different from when compiled on android to apk, based on testing

**Comment by travist** [comment]
Oh, I see... you are loading the JSON but the spinner never goes away? This does need to be fixed if that is the case.

**Comment by mtsang** [comment]
yes. that's right. it's loading from JSON but spinner is still there...

Aside, when i am able, i will try to help you track down #90 --prod, but it is exceedingly opaque to debug. Aside from than that, i thought i would share my own prioiritized wish list of ng2-formio fixes :) 

#94 (bad binding of data of radio/checkbox labels in datagrid)
#107 ( custom classes are not coming through ng2-formio)
#102 (- dual entries on datagrid, which is still broken but currently listed as a closed ticket)
#83 (custom events not emitted)

**Comment by travist** [comment]
Should be fixed in RC18.
