### ISSUE TITLE
every time a page is loaded, datagrids seem to add another data row

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#110]
eg. https://auicqnmuwlxvnoh.form.io/form3

just flipping back and forth on wizard adds more lines to datagrids. same with repeatedly saving and reloading data on normal form view. it may have to do with the bug where it's displaying one more datagrid field than it should to begin with (#102) 

(p.s. thank you for your excellent work with the checkbox/radios. they seem to work well with rc18)

**Comment by travist** [comment]
RC19 fixes this.

**Comment by mtsang** [comment]
fix confirmed!
