### ISSUE TITLE
request - css class on wizard buttons (cancel, next etc.)

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#111]
will make it easier to style / hide them if not needed

**Comment by mtsang** [comment]
even better if each button has a different class or id.
(also nice if we have the option to show the navigation links on the bottom)

**Comment by travist** [comment]
I am adding the following classes.

```
btn-wizard-nav-cancel
btn-wizard-nav-previous
btn-wizard-nav-next
btn-wizard-nav-submit
```

**Comment by travist** [comment]
RC19 fixes this.
