### ISSUE TITLE
conditionally hidden fields are never shown for (android, iOS) compiled apps (permanently not showing whether or not they are hide on event or show on event)

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#112]
not sure how to go about debugging this. if there is something i can do, please let me know!

**Comment by mtsang** [comment]
fields either are either permanently shown, or never show, even though running on web  / livereload  works fine

**Comment by travist** [comment]
I will need to hook up an app with GapDebug to get to the bottom of this. Are you using Ionic?

**Comment by mtsang** [comment]
yes, using ionic

**Comment by mtsang** [comment]
I'm trying to create a demo ionic project for you... 

when i try to compile there is an error. following suggestion from Toub on https://github.com/webpack/webpack/issues/4072

we can see it's trying to find ng2-formio/dist/formio.config which doesn't exist ... do you have an old reference somewhere?

File not found:  HarmonyImportDependency {
  module: null,
  request: 'ng2-formio/dist/formio.config',
  userRequest: 'ng2-formio/dist/formio.config',
  range: [ 1065, 1129 ],
  importedVar: '__WEBPACK_IMPORTED_MODULE_9_ng2_formio_dist_formio_config__',
  loc: SourceLocation { index: -1 } }

**Comment by mtsang** [comment]
ignore previous comment. it was my bad in the app using a previous rc

**Comment by mtsang** [comment]
@travist  loading using raw JSON fails with hidden fields

I have compiled an apk here that you can try: https://filebin.ca/3NwPF1pQLhSr/test.apk

The following code is the key piece, rending the form twice, one using server, the other using JSON.
```
<formio src='https://auicqnmuwlxvnoh.form.io/form4'></formio> 
<formio [form]='{"components":[{"key":"panel2","input":false,"title":"","theme":"default","components":[{"conditional":{"eq":"","when":null,"show":""},"tags":[],"type":"checkbox","validate":{"required":false},"clearOnHide":true,"value":"","name":"","hidden":false,"persistent":true,"protected":false,"defaultValue":false,"key":"showdatagrid","datagridLabel":true,"label":"show datagrid","hideLabel":true,"tableView":true,"inputType":"checkbox","input":true},{"conditional":{"eq":"true","when":"showdatagrid","show":"true"},"tags":[],"type":"datagrid","clearOnHide":true,"hidden":false,"persistent":true,"protected":false,"key":"datagrid","label":"datagrid","tableView":true,"components":[{"conditional":{"eq":"","when":null,"show":""},"tags":[],"hideLabel":true,"type":"columns","columns":[{"components":[{"tags":[],"hideLabel":true,"type":"textfield","conditional":{"eq":"","when":null,"show":""},"validate":{"customPrivate":false,"custom":"","pattern":"","maxLength":"","minLength":"","required":false},"clearOnHide":true,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":"","placeholder":"","key":"name","label":"name","inputMask":"","inputType":"text","tableView":true,"input":true}]},{"components":[{"tags":[],"type":"textfield","conditional":{"eq":"","when":null,"show":""},"validate":{"customPrivate":false,"custom":"","pattern":"","maxLength":"","minLength":"","required":false},"clearOnHide":true,"hidden":false,"persistent":true,"unique":false,"protected":false,"defaultValue":"","multiple":false,"suffix":"","prefix":""  ,"placeholder":"","key":"yodel","label":"yodel","inputMask":"","inputType":"text","tableView":true,"input":true}]}],"key":"columns","input":false}],"tree":true,"input":true}],"type":"panel","tags":[],"conditional":{"show":"","when":null,"eq":""}}],"type":"panel","tags":[],"conditional":{"show":"","when":null,"eq":""}}'> </formio>
```
I can share the code with you if that would help.

The first instance of the form works fine. the JSON version of the form immediately after does not.

**Comment by mtsang** [comment]
code is available here 
https://github.com/mtsang/formiobuildissue.git

running build.sh should build it..

**Comment by mtsang** [comment]
In addition, it appears as though loading data into the form also doesn't work if loaded from JSON (when it is built to ios or android...)

**Comment by mtsang** [comment]
@travist, does the ng2-formio component know how to read from a src=file:// URI ? 
(thinking of using this workaround until the root issue gets resolved...)

**Comment by mtsang** [comment]
this is fixed with rc.33
