### ISSUE TITLE
missing formiojs/full in compilation for rc.25

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#119]
Error: ./~/ng2-formio/src/formio.component.js Module not found: Error: Can't resolve 'formiojs/full'

**Comment by travist** [comment]
Sorry about that. Delete your node_modules and try again. Had a few upgrade hiccups this morning. It should be pulling in formiojs:2.9.3 which includes the fix.

**Comment by mtsang** [comment]
[16:37:22]  Error: ./~/formiojs/build/components/base/Base.js Module not found: Error: Can't resolve 
            'text-mask-all/vanilla'



Module not found: Error: Can't resolve 'text-mask-all/addons/dist/createNumberMask' in node_modules/formiojs/build/components/currency'

**Comment by travist** [comment]
Ok thanks. Been doing a lot of restructuring. Will look at this tonight.

**Comment by travist** [comment]
I have been having a hard time reproducing this error. I just pulled down a fresh install of ng2-app-starterkit, booted it up, and then added some fields that require text mask and it seems to be working fine.

https://monosnap.com/file/VvvWjOgnX30X3L6JjK7rwJuy1sXsjf

Can you please provide me a path to reproduce your errors?

**Comment by mtsang** [comment]
https://github.com/mtsang/issue-1.git  branch brokenrc25

npm i
you'll need to touch node_modules/ng2-formio/src/formio.component.css first as it's missing, 
then run 
npm run ionic:build --prod

**Comment by mtsang** [comment]
with the code, you should be able to reproduce... let me know if you have trouble..

**Comment by mtsang** [comment]
still an issue with rc.1.0.0-28
