### ISSUE TITLE
Programmatically populate an ng2-formio

### ISSUE THREAD

**Issue by micmanc** [formio/ng2-formio#26]
Is there a way to programmatically populate with data the input fields of an ng2-formio component? 
I included the ng2-formio component in an Angular2 application through the following line:

<formio [form]="form" (render)="onRender()" (submit)="onSubmit($event)" (change)="onChange($event)" ></formio>

where form points to the JSON schema of a form built on Form.io. 
Thanks

**Comment by travist** [comment]
Hello @micmanc, we are working on adding that feature soon where you can pass in the submission object much like you can with the Angular 1 renderer.

**Comment by travist** [comment]
Hello @micmanc this is now available in version 0.3.0. Here is how to use it.

https://github.com/formio/ng2-formio/blob/master/example/app.component.ts#L9
https://github.com/formio/ng2-formio/blob/master/example/app.html#L2

**Comment by bittencourtlima** [comment]
Hey @travist, the above examples are not opening, could you pass more examples?
Need to know how do I get my Rest API to be called and populate the FormIO components manually?

**Comment by bittencourtlima** [comment]
Hey @travist, the above examples are not opening, could you pass more examples?
Need to know how do I get my API Rest to call and fill the FormIO components manually using Angular 5 or Angular 2?
