### ISSUE TITLE
[submission]="submission"  data is not binding after callback function

### ISSUE THREAD

**Issue by ohanraj** [formio/ng2-formio#29]
now i updated the module ,
now it binds value but ,

# at Init the value for it binds 
```
public submission: any = {
//       data: {
//           user: {
//               firstName: 'Joe',
//               lastName: 'Smith',
//               email: 'joe@example.com',
//               kids: [
//                   'Susie',
//                   'Jack'
//               ]
//           },
//           cars: [
//               {
//                   make: 'Jeep',
//                   model: 'Wrangler',
//                   year: '2010'
//               },
//               {
//                   make: 'Ford',
//                   model: 'Mustang',
//                   year: '2014'
//               }
//           ]
//       }
//     };
```

 **It does not bind the value after a the call back funtion (service call and response)**
```

this.cs.getById(editid,this.collectionName).subscribe(custdata=>{
this.submission.data=custdata.data;

                console.log(this.submission.data);
                
             });
```
## ng2formio load before submission data bind
ng2formio load before submission data bind

**Comment by travist** [comment]
Do you have a value for ```submission```?

As you can see in our Examples, this should be working https://github.com/formio/ng2-formio/blob/master/example/app.html. 

Let me know more information to your use case please.

**Comment by ohanraj** [comment]
now i updated the module ,
now it binds value but , It does not bind the value after a the call back funtion (service call and response)

this.cs.getById(editid,this.collectionName).subscribe(custdata=>{
                    debugger;         
                    //if(custdata.data)
                    this.submission.data=custdata.data;
                    
                   // this.init(custdata.data);
                    console.log("1");
                    console.log(this.submission.data);
                    //  (<FormGroup>this.form).setValue(custdata.data, { onlySelf: true });
                    
                 })

**Comment by ohanraj** [comment]
`<formio ***ngIf="showForm"** [form]="form" [submission]="submission" (render)="onRender()" (submit)="onSubmit($event)" (change)="onChange($event)"></formio>`

issue resolved ...
by giving ngIf="showForm" and make condition this.showForm=true in  formio after callback function load 

It worked for me

Thanks for help travist
