### ISSUE TITLE
 Example does not work: checkCondition is not a function 

### ISSUE THREAD

**Issue by harryhahn** [formio/ng2-formio#31]
The example use  checkCondition: from   'formio-utils' 
in version 0.1.10 it doesnt exist. 
Correct the package.json to  0.2.3 and it works.

**Comment by manishkumar-tudip** [comment]
Updated formio-utils to 0.2.3
This will be fixed after merging formio-wizard-alerts branch into master.

**Comment by travist** [comment]
Fixed in 0.4.0
