### ISSUE TITLE
data does not stored into DB

### ISSUE THREAD

**Issue by srinathswaminathan** [formio/ng2-formio#44]
hi,
 i am using ng2-formio, when i want to save my form in DB,but the form created with no fields

like:
{ 
    "_id" : ObjectId("587638b84de6661f7cba09fb"), 
    "hiddenField2" : null, 
    "partner_id" : ObjectId("58294d8f0a0a17144c0d9ced"), 
    "status" : "1", 
    "__v" : NumberInt(0)
}

**Comment by ohanraj** [comment]
I also facing same issue ,

But we Found that data are not bind, **when it been design inside the panel body**

outside panel body field data  are binding 

Issue In getting data field from panel body 

Please help....

**Comment by travist** [comment]
Thanks for reporting. Will look into it and hope to have a new version out by the end of the week with this resolved.  Thanks!

Travis.

**Comment by srinathswaminathan** [comment]
Hi,
with in a panel the data does not pass,just remove the panel use the fields and then the data will passing.
thank you

**Comment by travist** [comment]
We will still look into this. The data should be passing when the fields are within a panel.

**Comment by travist** [comment]
I did just find an issue with panels as well as all other "container" type fields with data. I just pushed up a new version 0.9.0 that fixes this problem. Thanks!
