### ISSUE TITLE
Error in datetime.ts

### ISSUE THREAD

**Issue by harryhahn** [formio/ng2-formio#48]
In Version 0.7.0 an error show

...node_modules/ng2-formio/src/components/datetime/datetime.ts (54,9): Cannot invoke an expression whose type lacks a call signature.

**Comment by travist** [comment]
Hello @harryhahn I am aware of issues with the datetime and am looking into fixing it soon. The reason it is taking me longer than usual is I am in the process of replacing the datetime implementation with using flatpickr instead.  https://github.com/chmln/flatpickr

**Comment by travist** [comment]
This is now resolved with beta.1 release!  We are now using the flatpickr module which is much easier to deal with.
