### ISSUE TITLE
datepicker module issue

### ISSUE THREAD

**Issue by srinathswaminathan** [formio/ng2-formio#51]
while i update the  latest version of  ng2-formio 0.9.0, issue will occur, at the same time when i use ng2-formio 0.7.0 its working normally.
what is the solution?

issue:
Error: (SystemJS) ng2_bootstrap_1.DatepickerModule.forRoot is not a function
	   TypeError: ng2_bootstrap_1.DatepickerModule.forRoot is not a function

**Comment by travist** [comment]
This seems like it may be pulling in an old version of the Datepicker and Timepicker module before they implemented the ```forRoot```

**Comment by srinathswaminathan** [comment]
ya ok, then how to use update ng2-formio?
what can i have to chenge on my code

**Comment by travist** [comment]
I would delete the ```node_modules``` folder and then run ```npm install``` again. Let me know if that works.

**Comment by travist** [comment]
This is now resolved with beta.1 release!  We are now using the flatpickr module which is much easier to deal with.
