### ISSUE TITLE
Formio Service Extensibility - Bug fix

### ISSUE THREAD

**Issue by anupriya7295** [formio/ng2-formio#59]
Hi Travis,
      Thank you for the quick response regarding  [issue #57](https://github.com/formio/ng2-formio/issues/57).

As per your instructions I extended core _FormioService_ class in my own Service class and passed that service variable to `<formio>` directive but code flow gets stuck in _FormioComponent ngOnInit()_.
        
This is because when compiler sees `<formio>` directive it automatically invokes _Formio.Component_ core class after which _ngOnInit()_ function gets executed where there are 2 conditions:
1) this.form 
2) this.src && !this.service
After this flow is terminated as there is no condition for both src and service.

     I have raised pull request solving this issue [Bugfix/FormioComponent #58](https://github.com/formio/ng2-formio/pull/58) where I have extended formio service in following way
**## HTML**
                             `<formio src="test.json" service="ExtFormioService"></formio>`
**## component**
```
export class AppComponent {
    @Input() src: string;
    @Input() service: ExtFormioService;   //Extended formioservice class 
    constructor() {
      this.src = 'test.json';
      this.service = new ExtFormioService(this.src);
    }
}
```
 **## Extended Service**
```
export class ExtFormioService extends FormioService {
constructor(public src: string) {
super(src);
return this;
} 
}
```
Consider merging the pull request with your formio master. Please let me know your comments.

**Comment by travist** [comment]
This is now resolved with beta.1 release!
