### ISSUE TITLE
[BUG] Column Element: Error throws up while adding elemnts to a column element.

### ISSUE THREAD

**Issue by PranapSivadasan** [formio/ng2-formio#608]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: **Latest**
- Frontend framework: **Angular**
- Browser: **Firefox**
- Browser version: **79.0**

## Steps to Reproduce
1.  Add a column element in the form.
2.  Add a any other element in one of the column. 
        **For example:** Add a Text field inside the column.
3.  As soon as an element is added, the error is thrown up in the console.
4.  When trying to edit the added element, an other error is thrown.
        **For example:** Try to change the label of the text field.

## Expected behavior

No error must be thrown while adding or editing an element in the column.

## Observed behavior

Error is thrown while adding or editing an element in the column.

## Example
![Formio_error](https://user-images.githubusercontent.com/44242289/90890670-10a65a00-e3d8-11ea-86c9-0d9d5a05db26.gif)

**Comment by travist** [comment]
Thanks we will take a look.

**Comment by wag110894** [comment]
@PranapSivadasan,

We have created a ticket for this issue. For reference, the ticket number is FJS-1186. We will be taking a look at this when we are working on the next build of the Angular Demo. 

We will let you know once this is resolved.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
