### ISSUE TITLE
Formio Wizard not rendering

### ISSUE THREAD

**Issue by anupriya7295** [formio/ng2-formio#63]
Wizard not rendering if input given as  src 
`<formio src="test.json"></formio>`

**Comment by travist** [comment]
```src``` needs to be a web accessible file and not local to the application. If you wish to show raw JSON, then I would recommend setting a variable within the controller, and then passing that variable into the template to render the form using the ```[form]``` parameter like so.

```ts
@Component({
  template: '<formio [form]="myform"></formio>'
})
export class MyComponent {
  myform: any = {}; // INPUT FORM SCHEMA HERE
}
```
