### ISSUE TITLE
Error [...]  resolving symbol FormioModule in /.../formioApp/node_modules/ng2-formio/dist/index.d.ts

### ISSUE THREAD

**Issue by DigitalOak** [formio/ng2-formio#72]
I did following steps:

1. npm install -g @angular/cli
2. ng create formioApp
3. cd formioApp
4. Modify files as in https://github.com/formio/ng2-formio/wiki/1.)-Form-Renderer
5. ng serve --host 0.0.0.0 --port 8080

`ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 2:22 in the original .ts file), resolving symbol FormioModule in /home/ubuntu/workspace/formioApp/node_modules/ng2-formio/dist/index.d.ts, resolving symbol AppModule in /home/ubuntu/workspace/formioApp/src/app/app.module.ts, resolving symbol AppModule in /home/ubuntu/workspace/formioApp/src/app/app.module.ts`

**Comment by travist** [comment]
What version of Angular/TypeScript are you using? I am about to release an RC1 that I am sure will clear most of these compile issues.

**Comment by DigitalOak** [comment]
Angular - 2.4.10
Typescript - 2.0.10
I'm testing it on Cloud9 workspace, if you give me your email I can share it with you with RW rights.

**Comment by travist** [comment]
Sure... email is travis@form.io

**Comment by DigitalOak** [comment]
You have to first create an account on c9.io.

**Comment by travist** [comment]
I logged in through github, so try again.

**Comment by harryhahn** [comment]
i have  the same issue

**Comment by travist** [comment]
Should be fixed with RC5.

**Comment by jhonvedo** [comment]
hi. it is late but  I had this problem and I resolved erasing the folder node_modules within ng2-formio.
I hope it helps them.

**Comment by faustotnc** [comment]
@jhonvedo Thanks a lot!!! that did solve the problems for me.  I had a similar issue with ng2-typewriter.
