### ISSUE TITLE
Selection box

### ISSUE THREAD

**Issue by krixerx** [formio/ng2-formio#73]
<formio [form]="selectionData" class="formio"></formio>

selectionData input value is:
"values":[{"value":"vvvv","label":"vvvv"}]

after form uploading the value is:
"values":[{"id":undefined,"text":undefined}]

**Comment by travist** [comment]
This should be fixed in the RC1 release which is coming. This release will use the core renderer which includes fixes to the select component.

**Comment by krixerx** [comment]
Selection works properly with version RC1
