### ISSUE TITLE
Is this an Angular Component as a wrapper around react-formio?

### ISSUE THREAD

**Issue by rjsteinert** [formio/ng2-formio#82]
I'm trying to understand how this library is put together so I might be able to contribute back. My initial impression is that this is a Angular Component that wraps react-formio. Is that right?

**Comment by StephenOTT** [comment]
![screen shot 2017-04-05 at 7 50 58 pm](https://cloud.githubusercontent.com/assets/1994838/24731670/85c5fae6-1a39-11e7-8c0b-69320e309dd3.png)

They wrap around formio.js

**Comment by rjsteinert** [comment]
I see now on [this line](https://github.com/formio/ng2-formio/blob/master/src/formio.component.ts#L8) that the Angular FormioComponent is a wrapper around the `formiojs` package that lives in [this repository](https://github.com/formio/formio.js). I'm uncertain how `this.formio` ends up in the DOM. Can you help me understand how that works?

**Comment by rjsteinert** [comment]
Is it [this line](https://github.com/formio/ng2-formio/blob/master/src/formio.component.ts#L101) that does the magic?

**Comment by rjsteinert** [comment]
Ah yes, I can see on that line, `this.elementRef.nativeElement` is the actual DOM element of the Angular Component.

![screen shot 2017-05-23 at 4 01 25 pm](https://cloud.githubusercontent.com/assets/156575/26373966/8c20b508-3fd1-11e7-81d3-6847c8432144.png)

I also see in the `formiojs` package that [the `setElement` function](https://github.com/formio/formio.js/blob/0b25a602dfbc19603ed4f577e3c70d99838487d6/src/formio.form.js#L173) uses the element passed into it "to set as the outside wrapper element for this form."

Using ElementRef is an interesting approach and makes sense for a pure JS library to use to latch onto the DOM in a way it is used to doing. The Angular team puts a [big red warning](https://angular.io/docs/js/latest/api/core/index/ElementRef-class.html) on its use. I wonder if they'll keep it around. I bet they'd like to get rid of it but it might be one of those things where there would be too many people complaining and always an edge case that justifies its use.
