### ISSUE TITLE
Trying hello world example I get error "ERROR Error: No provider for FormioAppConfig!"

### ISSUE THREAD

**Issue by rjsteinert** [formio/ng2-formio#89]
## Setup
1. Get a fresh install of `ng-cli`.
2. Run `ng new formio-hello-world && cd formio-hello-world && npm install ng2-formio && npm start` 
3. As seen in the ng2-formio README, add the two import statements in `app.module.ts`.
4. As seen in the ng2-formio README, add the formio component to your `app.component.html` using the URL example.

## Behavior

<img width="1280" alt="screen shot 2017-05-01 at 2 16 18 pm" src="https://cloud.githubusercontent.com/assets/156575/25578577/ccfb37e8-2e78-11e7-8b14-e74d1322ba37.png">

**Comment by travist** [comment]
This should be fixed with RC3. Thanks.

**Comment by travist** [comment]
I fixed the FormioModule issue with AOT in RC5, so use that one instead.

**Comment by rjsteinert** [comment]
Using RC17 today works great. Thanks @travist.
