### ISSUE TITLE
Data Grid Component don't work correct

### ISSUE THREAD

**Issue by harryhahn** [formio/ng2-formio#92]
I design a form in Form.io. Is works correct in the form.io platform.

If we use the same form with ng2-formio the form does not work properly (check with ng2-app-starterkit).
after NEW:

- the select component is empty and not correct 
- then other fields are duplicated with the value of the first row

here the form 
   https://emnesvhpqqyezrm.form.io/hgkontakt2

and the screenshot
![image](https://cloud.githubusercontent.com/assets/7956253/25906045/eff18a04-35a3-11e7-87ca-17985de32810.png)

**Comment by travist** [comment]
Thanks @harryhahn for reporting. I will take a look as soon as possible.

**Comment by mtsang** [comment]
have also experienced this from time to time. have not figured out how to reproduce consistently

**Comment by mtsang** [comment]
For me, starting with 3  blank items in the datagrid, filling in the first text item of a datagrid and then adding a 4th item will cause all the other items (2,3,4) to take on the value of the first one.
Same with removing one in an array of datagrid items. all of the remaining ones take the value of the first one. 

May also be related to  issue #94, where there seems to be inappropriate binding to the first item

**Comment by travist** [comment]
Please try the latest version RC14 and let me know if this is resolved.

**Comment by harryhahn** [comment]
GREAT
it works.
thanks
