### ISSUE TITLE
radio/checkbox lables in datagrid bound to first item

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#94]
clicking on a *label* for radio buttons or checkboxes will select option on the first item in a datagrid, even if the user is clicking on the 2nd or 3rd datagrid entry. 

However, clicking directly on the box (checkbox) or  circle (for radio) works as expected

behaviour as at rc.12

**Comment by travist** [comment]
Please try the latest version RC14 and let me know if this is resolved.

**Comment by mtsang** [comment]
Thanks for your work - unfortunately rc14 still has the issues: 

Some additional context to help:

Panel->datagrid->column->radio/checkbuttons (inside a column in a datagrid inside a panel)
  clicking radio label doesn't do anything 
  clicking radio circle on any item will remove any selection from all other instances of the same radio item

Panel->Datagrid->radiobutton (datagrid inside a panel)
  -> clicking on an any radiobutton instance will select the first instance's equivalent radiobutton

**Comment by travist** [comment]
Is there any way we can get a form URL that illustrates these problems?

**Comment by mtsang** [comment]
yes. same form URL listed in #95 accompanying video also shows it

**Comment by travist** [comment]
I can reproduce, but this may be a input name key issue. I will try to get it fixed in next version.

**Comment by mtsang** [comment]
thx. let me know when it's fixed and i can help to test

**Comment by mtsang** [comment]
i think you are right. in datagrids, the generated checkboxes all have an 'undefined' prefix, which is why all the subsequent ones bind to the first one when you click the labels. there are multiple checkboxes all with the same undefined-<value> id. 
<label class="control-label" for="undefined-yes"><input name="data[name1]name2][]" type="checkbox" class="" id="undefined-yes" value="yes">Yes</label>

**Comment by mtsang** [comment]
update: in datagrid, clicking on any radio button (any part of it) will  change the first of the datagrid set

**Comment by travist** [comment]
Thanks @mtsang . I will look into this as soon as possible.

**Comment by travist** [comment]
Should be fixed in RC18.
