### ISSUE TITLE
unable to install angular-formio in Angular 15.2.4 solution

### ISSUE THREAD

**Issue by subash-arveti** [formio/ng2-formio#947]
Unable to install the package on latest angular frame work. when tried to execute "**npm install angular-formio --save**".
Its throwing dependency errors as shown below. 
![image](https://user-images.githubusercontent.com/110967979/227993539-1dd4ba4a-2b6c-412c-a5ea-9194899b1709.png)

Can some one help me how to resolve this issue

**Comment by subash-arveti** [comment]
Hi @brendanbond 

I tried even with that solution but got the below error.

![image](https://user-images.githubusercontent.com/110967979/227998700-31f84bf8-1642-42e9-9df8-d79fb8220b1d.png)

can you please suggest me like do i need to go with any specific version?

**Comment by brendanbond** [comment]
oh, try --legacy-peer-deps when you npm install
