### ISSUE TITLE
BUTTON Component: custom event don't fire

### ISSUE THREAD

**Issue by harryhahn** [formio/ng2-formio#96]
when we use in ACTION = event in a Button Component, the event don't fire. 
The page was reload. 
I use rc14 and test it in Chrome and Firefox (both newest Versions)

**Comment by mtsang** [comment]
related to #83

**Comment by travist** [comment]
There is now a ```(customEvent)``` parameter that can be attached to the ```<formio>``` directive where you can receive custom events from the buttons. Let me know if this works.

**Comment by travist** [comment]
RC19 fixes this.

**Comment by swliu920322** [comment]
sorry, i can't find customEvent, how should i use it

**Comment by alexrok21** [comment]
how do you emit a custom event?
