### ISSUE TITLE
Radio Button: default value not visible

### ISSUE THREAD

**Issue by harryhahn** [formio/ng2-formio#97]
in a radio button component the default value not visible. The change event fired after loading but the 'Yes' is not selected. And the value in the Object not set.
I design a form in Form.io. Is works correct in the form.io platform.

![image](https://cloud.githubusercontent.com/assets/7956253/26025741/779adb6c-37ee-11e7-9477-9b62653ecd30.png)

here the form
https://emnesvhpqqyezrm.form.io/hgkontakt

**Comment by travist** [comment]
Thanks for letting me know. I will look into it over the weekend.

**Comment by travist** [comment]
Should be fixed in RC15.
