### ISSUE TITLE
datagrid that is conditionally shown has labels set to 'undefined'

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#98]
context:
for a datagrid within a panel, setting it to be conditionally displayed on a checkbox will display te label as "undefined" when it appears

expected behaviour: should show the proper label (correct behaviour exhibited by  ng-formio )

**Comment by travist** [comment]
Will you please provide a JSON url of the form so that I can easily reproduce?

**Comment by mtsang** [comment]
hi, the behaviour is exhibited on this form when rendered with ng2-formio
https://auicqnmuwlxvnoh.form.io/form1

(look for the 'undefined' fields when you click on the checkboxes)

**Comment by mtsang** [comment]
@travist (is the above good enough for reproduction?)

**Comment by travist** [comment]
Yep. Perfect. I am on it now and should have an update within the next day or so.

**Comment by travist** [comment]
Should be fixed in RC15.
